#!/bin/sh

# ---------------------------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------------------------------------------------

lvm_enabled() {
	if ! lvscan |grep -i -w "inactive" &>/dev/null;then
		return 1
	fi
	return 0
}

lvm_run() {
	lvm pvscan --cache --activate ay
	lvm vgscan --mknodes
	udevadm trigger --action=add
}
