#!/bin/sh -e

BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE MACHINE http_proxy ftp_proxy https_proxy \
                   all_proxy ALL_PROXY no_proxy GIT_PROXY_COMMAND \
                   GIT_PROXY_IGNORE SOCKS5_PASSWD SOCKS5_USER SCREENDIR"
export BB_ENV_EXTRAWHITE

. "$(dirname "$0")/wrap"
wrap $0 "$@"
