#!/bin/sh

set -u

if [ $(id -u) -ne 0 ]; then
    echo >&2 "Verifying access to sudo, please enter your password if prompted."
    sudo -v
    if [ $? -ne 0 ]; then
        echo >&2 "Could not use sudo, exiting"
        exit 1
    fi
    exec sudo "$0" "$@"
fi

set -- \
    binutils \
    bzip2 \
    ca-certificates \
    chrpath \
    cpio \
    cpp \
    diffstat \
    file \
    g++ \
    gawk \
    gcc \
    git \
    libc-dev-bin \
    locales \
    make \
    patch \
    python3 \
    python3-distutils \
    rsync \
    wget \
    ssh

# This is helpful to write images, and is in our documentation
set -- "$@" bmap-tools

echo >&2 "Installing packages.."
apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y -f --no-install-recommends "$@"

echo >&2 "Generating the en_US.UTF-8 locale"
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

echo >&2 "Setup complete"
