#!/bin/sh
#
# Copyright 2021 Siemens
#
# This file is licensed under the terms of the GNU General Public License
# version 2.  This program  is licensed "as is" without any warranty of any
# kind, whether express or implied.

packages="python38 \
          patch diffstat git bzip2 tar \
          gzip gawk chrpath wget cpio perl file which \
          make gcc gcc-c++ rsync rpcgen"

set -e

if [ "$(id -u)" != "0" ]; then
    echo "Verifying access to sudo, please enter your password if prompted."
    if ! sudo -v; then
        echo >&2 "Could not use sudo, exiting"
        exit 1
    fi
    exec sudo "$0" "$@"
fi

echo "Enabling any required repos"
if grep -q "^CentOS" /etc/redhat-release 2>/dev/null; then
    dnf config-manager --set-enabled PowerTools
fi

echo "Installing packages required to build Mentor Embedded Linux Flex OS"
dnf install "$@" $packages || {
    echo >&2 "Error installing our required packages, aborting"
    exit 1
}
echo "Setup complete"
