#!/bin/sh
#
# Copyright 2007-2012 Mentor Graphics Corporation
#
# This file is licensed under the terms of the GNU General Public License
# version 2.  This program  is licensed "as is" without any warranty of any
# kind, whether express or implied.

packages="make gcc gcc-c++ patch texi2html diffstat texinfo tetex cvs git
          subversion gawk tar gzip bzip2 redhat-lsb sqlite ncurses-devel \
          SDL-devel"
scriptsdir="$(cd $(dirname $0) && pwd)"

set -e

is_installed () {
    rpm -q "$@" >/dev/null 2>&1
}

echo "Verifying access to sudo, please enter your password if prompted."
if ! sudo -v; then
        echo "Could not use sudo, exiting"
        exit 1
fi

if ! is_installed epel-release; then
    cd $scriptsdir
    wget http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm || {
        echo >&2 "Unable to download epel-release, aborting"
        exit 1
    }

    trap "rm -f $scriptsdir/epel-release-5-4.noarch.rpm" EXIT
    sudo rpm -ivh epel-release-5-4.noarch.rpm || {
        echo >&2 "Unable to install epel-release, so unable to install python 2.6, aborting"
        exit 1
    }
fi

if ! is_installed python26; then
    packages="$packages python26"
fi

if ! is_installed chrpath; then
    packages="$packages chrpath"
fi

echo "Installing packages required to build Mentor Embedded Linux"
sudo yum -y install $packages || {
    echo >&2 "Error installing our required packages, aborting"
    exit 1
}

echo "Installing symlink /usr/local/bin/python -> /usr/bin/python2.6"
sudo ln -s /usr/bin/python2.6 /usr/local/bin/python

echo "Setup complete"
