#!/bin/sh

set -e

PSEUDO_UNLOAD=1 qemuwrapper -L $D -E LD_LIBRARY_PATH=$D${libdir}:$D${base_libdir} \
        $D${libexecdir}/${binprefix}gio-querymodules $D${libdir}/gio/modules/

# If no modules are installed, no cache file will be written
if [ -e $D${libdir}/gio/modules/giomodule.cache ]; then
    chown root:root $D${libdir}/gio/modules/giomodule.cache
fi

